// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppConfig struct {
	ID                  int32            `db:"id" json:"id"`
	Platform            string           `db:"platform" json:"platform"`
	ConfigData          []byte           `db:"config_data" json:"config_data"`
	SportotoProgramName pgtype.Text      `db:"sportoto_program_name" json:"sportoto_program_name"`
	PayinEndDate        pgtype.Timestamp `db:"payin_end_date" json:"payin_end_date"`
	NextDrawExpectedWin pgtype.Numeric   `db:"next_draw_expected_win" json:"next_draw_expected_win"`
	CreatedAt           pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type BettingVolumeHistory struct {
	ID                 int32            `db:"id" json:"id"`
	EventID            pgtype.Int4      `db:"event_id" json:"event_id"`
	VolumePercentage   pgtype.Numeric   `db:"volume_percentage" json:"volume_percentage"`
	RankPosition       pgtype.Int4      `db:"rank_position" json:"rank_position"`
	TotalEventsTracked pgtype.Int4      `db:"total_events_tracked" json:"total_events_tracked"`
	RecordedAt         pgtype.Timestamp `db:"recorded_at" json:"recorded_at"`
}

type BigMover struct {
	ID                   int32            `db:"id" json:"id"`
	EventID              pgtype.Int4      `db:"event_id" json:"event_id"`
	MarketTypeID         pgtype.Int4      `db:"market_type_id" json:"market_type_id"`
	Outcome              string           `db:"outcome" json:"outcome"`
	OddsValue            pgtype.Numeric   `db:"odds_value" json:"odds_value"`
	PreviousValue        pgtype.Numeric   `db:"previous_value" json:"previous_value"`
	WinningOdds          pgtype.Numeric   `db:"winning_odds" json:"winning_odds"`
	ChangeAmount         pgtype.Numeric   `db:"change_amount" json:"change_amount"`
	ChangePercentage     pgtype.Numeric   `db:"change_percentage" json:"change_percentage"`
	Multiplier           pgtype.Numeric   `db:"multiplier" json:"multiplier"`
	RecordedAt           pgtype.Timestamp `db:"recorded_at" json:"recorded_at"`
	SharpMoneyIndicator  pgtype.Numeric   `db:"sharp_money_indicator" json:"sharp_money_indicator"`
	IsReverseMovement    pgtype.Bool      `db:"is_reverse_movement" json:"is_reverse_movement"`
	SignificanceLevel    pgtype.Text      `db:"significance_level" json:"significance_level"`
	MinutesToKickoff     pgtype.Int4      `db:"minutes_to_kickoff" json:"minutes_to_kickoff"`
	EventExternalID      string           `db:"event_external_id" json:"event_external_id"`
	HomeTeamID           pgtype.Int4      `db:"home_team_id" json:"home_team_id"`
	AwayTeamID           pgtype.Int4      `db:"away_team_id" json:"away_team_id"`
	EventDate            pgtype.Timestamp `db:"event_date" json:"event_date"`
	EventStatus          string           `db:"event_status" json:"event_status"`
	IsLive               pgtype.Bool      `db:"is_live" json:"is_live"`
	MarketCode           string           `db:"market_code" json:"market_code"`
	MarketName           string           `db:"market_name" json:"market_name"`
	LeagueName           pgtype.Text      `db:"league_name" json:"league_name"`
	SportName            pgtype.Text      `db:"sport_name" json:"sport_name"`
	HomeTeamName         pgtype.Text      `db:"home_team_name" json:"home_team_name"`
	AwayTeamName         pgtype.Text      `db:"away_team_name" json:"away_team_name"`
	MinutesToKickoffCalc int32            `db:"minutes_to_kickoff_calc" json:"minutes_to_kickoff_calc"`
	AlertMessage         string           `db:"alert_message" json:"alert_message"`
}

type ContrarianBet struct {
	Slug          string         `db:"slug" json:"slug"`
	MatchName     interface{}    `db:"match_name" json:"match_name"`
	Market        interface{}    `db:"market" json:"market"`
	PublicChoice  string         `db:"public_choice" json:"public_choice"`
	PublicBacking interface{}    `db:"public_backing" json:"public_backing"`
	Odds          pgtype.Numeric `db:"odds" json:"odds"`
	OverbetBy     interface{}    `db:"overbet_by" json:"overbet_by"`
	Strategy      string         `db:"strategy" json:"strategy"`
}

type CurrentOdd struct {
	ID                 int32            `db:"id" json:"id"`
	EventID            pgtype.Int4      `db:"event_id" json:"event_id"`
	MarketTypeID       pgtype.Int4      `db:"market_type_id" json:"market_type_id"`
	Outcome            string           `db:"outcome" json:"outcome"`
	OddsValue          pgtype.Numeric   `db:"odds_value" json:"odds_value"`
	OpeningValue       pgtype.Numeric   `db:"opening_value" json:"opening_value"`
	HighestValue       pgtype.Numeric   `db:"highest_value" json:"highest_value"`
	LowestValue        pgtype.Numeric   `db:"lowest_value" json:"lowest_value"`
	WinningOdds        pgtype.Numeric   `db:"winning_odds" json:"winning_odds"`
	TotalMovement      pgtype.Numeric   `db:"total_movement" json:"total_movement"`
	MovementPercentage pgtype.Numeric   `db:"movement_percentage" json:"movement_percentage"`
	LastUpdated        pgtype.Timestamp `db:"last_updated" json:"last_updated"`
}

type Event struct {
	ID                      int32            `db:"id" json:"id"`
	ExternalID              string           `db:"external_id" json:"external_id"`
	LeagueID                pgtype.Int4      `db:"league_id" json:"league_id"`
	HomeTeamID              pgtype.Int4      `db:"home_team_id" json:"home_team_id"`
	AwayTeamID              pgtype.Int4      `db:"away_team_id" json:"away_team_id"`
	Slug                    string           `db:"slug" json:"slug"`
	EventDate               pgtype.Timestamp `db:"event_date" json:"event_date"`
	Status                  string           `db:"status" json:"status"`
	HomeScore               pgtype.Int4      `db:"home_score" json:"home_score"`
	AwayScore               pgtype.Int4      `db:"away_score" json:"away_score"`
	IsLive                  pgtype.Bool      `db:"is_live" json:"is_live"`
	MinuteOfMatch           pgtype.Int4      `db:"minute_of_match" json:"minute_of_match"`
	Half                    pgtype.Int4      `db:"half" json:"half"`
	BettingVolumePercentage pgtype.Numeric   `db:"betting_volume_percentage" json:"betting_volume_percentage"`
	VolumeRank              pgtype.Int4      `db:"volume_rank" json:"volume_rank"`
	VolumeUpdatedAt         pgtype.Timestamp `db:"volume_updated_at" json:"volume_updated_at"`
	BulletinID              pgtype.Int8      `db:"bulletin_id" json:"bulletin_id"`
	Version                 pgtype.Int8      `db:"version" json:"version"`
	SportID                 pgtype.Int4      `db:"sport_id" json:"sport_id"`
	BetProgram              pgtype.Int4      `db:"bet_program" json:"bet_program"`
	Mbc                     pgtype.Int4      `db:"mbc" json:"mbc"`
	HasKingOdd              pgtype.Bool      `db:"has_king_odd" json:"has_king_odd"`
	OddsCount               pgtype.Int4      `db:"odds_count" json:"odds_count"`
	HasCombine              pgtype.Bool      `db:"has_combine" json:"has_combine"`
	CreatedAt               pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type League struct {
	ID                 int32            `db:"id" json:"id"`
	ExternalID         string           `db:"external_id" json:"external_id"`
	Name               string           `db:"name" json:"name"`
	Country            pgtype.Text      `db:"country" json:"country"`
	SportID            pgtype.Int4      `db:"sport_id" json:"sport_id"`
	IsActive           pgtype.Bool      `db:"is_active" json:"is_active"`
	Slug               pgtype.Text      `db:"slug" json:"slug"`
	ApiFootballID      pgtype.Int4      `db:"api_football_id" json:"api_football_id"`
	LeagueType         pgtype.Text      `db:"league_type" json:"league_type"`
	LogoUrl            pgtype.Text      `db:"logo_url" json:"logo_url"`
	CountryCode        pgtype.Text      `db:"country_code" json:"country_code"`
	CountryFlagUrl     pgtype.Text      `db:"country_flag_url" json:"country_flag_url"`
	HasStandings       pgtype.Bool      `db:"has_standings" json:"has_standings"`
	HasFixtures        pgtype.Bool      `db:"has_fixtures" json:"has_fixtures"`
	HasPlayers         pgtype.Bool      `db:"has_players" json:"has_players"`
	HasTopScorers      pgtype.Bool      `db:"has_top_scorers" json:"has_top_scorers"`
	HasInjuries        pgtype.Bool      `db:"has_injuries" json:"has_injuries"`
	HasPredictions     pgtype.Bool      `db:"has_predictions" json:"has_predictions"`
	HasOdds            pgtype.Bool      `db:"has_odds" json:"has_odds"`
	CurrentSeasonYear  pgtype.Int4      `db:"current_season_year" json:"current_season_year"`
	CurrentSeasonStart pgtype.Date      `db:"current_season_start" json:"current_season_start"`
	CurrentSeasonEnd   pgtype.Date      `db:"current_season_end" json:"current_season_end"`
	ApiEnrichmentData  []byte           `db:"api_enrichment_data" json:"api_enrichment_data"`
	LastApiUpdate      pgtype.Timestamp `db:"last_api_update" json:"last_api_update"`
	CreatedAt          pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type LeagueMapping struct {
	ID                   int32            `db:"id" json:"id"`
	InternalLeagueID     int32            `db:"internal_league_id" json:"internal_league_id"`
	FootballApiLeagueID  int32            `db:"football_api_league_id" json:"football_api_league_id"`
	Confidence           pgtype.Numeric   `db:"confidence" json:"confidence"`
	MappingMethod        string           `db:"mapping_method" json:"mapping_method"`
	TranslatedLeagueName pgtype.Text      `db:"translated_league_name" json:"translated_league_name"`
	TranslatedCountry    pgtype.Text      `db:"translated_country" json:"translated_country"`
	OriginalLeagueName   pgtype.Text      `db:"original_league_name" json:"original_league_name"`
	OriginalCountry      pgtype.Text      `db:"original_country" json:"original_country"`
	MatchFactors         []byte           `db:"match_factors" json:"match_factors"`
	NeedsReview          pgtype.Bool      `db:"needs_review" json:"needs_review"`
	AiTranslationUsed    pgtype.Bool      `db:"ai_translation_used" json:"ai_translation_used"`
	NormalizationApplied pgtype.Bool      `db:"normalization_applied" json:"normalization_applied"`
	MatchScore           pgtype.Numeric   `db:"match_score" json:"match_score"`
	CreatedAt            pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type MarketType struct {
	ID                    int32            `db:"id" json:"id"`
	Code                  string           `db:"code" json:"code"`
	Name                  string           `db:"name" json:"name"`
	Slug                  string           `db:"slug" json:"slug"`
	Description           pgtype.Text      `db:"description" json:"description"`
	IddaaMarketID         pgtype.Int4      `db:"iddaa_market_id" json:"iddaa_market_id"`
	IsLive                pgtype.Bool      `db:"is_live" json:"is_live"`
	MarketType            pgtype.Int4      `db:"market_type" json:"market_type"`
	MinMarketDefaultValue pgtype.Int4      `db:"min_market_default_value" json:"min_market_default_value"`
	MaxMarketLimitValue   pgtype.Int4      `db:"max_market_limit_value" json:"max_market_limit_value"`
	Priority              pgtype.Int4      `db:"priority" json:"priority"`
	SportType             pgtype.Int4      `db:"sport_type" json:"sport_type"`
	MarketSubType         pgtype.Int4      `db:"market_sub_type" json:"market_sub_type"`
	MinDefaultValue       pgtype.Int4      `db:"min_default_value" json:"min_default_value"`
	MaxLimitValue         pgtype.Int4      `db:"max_limit_value" json:"max_limit_value"`
	IsActive              pgtype.Bool      `db:"is_active" json:"is_active"`
	CreatedAt             pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type MatchEvent struct {
	ID          int32            `db:"id" json:"id"`
	EventID     pgtype.Int4      `db:"event_id" json:"event_id"`
	Minute      int32            `db:"minute" json:"minute"`
	EventType   string           `db:"event_type" json:"event_type"`
	Team        string           `db:"team" json:"team"`
	Player      pgtype.Text      `db:"player" json:"player"`
	Description string           `db:"description" json:"description"`
	IsHome      bool             `db:"is_home" json:"is_home"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type MatchStatistic struct {
	ID            int32            `db:"id" json:"id"`
	EventID       pgtype.Int4      `db:"event_id" json:"event_id"`
	IsHome        bool             `db:"is_home" json:"is_home"`
	Shots         pgtype.Int4      `db:"shots" json:"shots"`
	ShotsOnTarget pgtype.Int4      `db:"shots_on_target" json:"shots_on_target"`
	Possession    pgtype.Int4      `db:"possession" json:"possession"`
	Corners       pgtype.Int4      `db:"corners" json:"corners"`
	YellowCards   pgtype.Int4      `db:"yellow_cards" json:"yellow_cards"`
	RedCards      pgtype.Int4      `db:"red_cards" json:"red_cards"`
	Fouls         pgtype.Int4      `db:"fouls" json:"fouls"`
	Offsides      pgtype.Int4      `db:"offsides" json:"offsides"`
	FreeKicks     pgtype.Int4      `db:"free_kicks" json:"free_kicks"`
	ThrowIns      pgtype.Int4      `db:"throw_ins" json:"throw_ins"`
	GoalKicks     pgtype.Int4      `db:"goal_kicks" json:"goal_kicks"`
	Saves         pgtype.Int4      `db:"saves" json:"saves"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type MovementAlert struct {
	ID               int32            `db:"id" json:"id"`
	OddsHistoryID    int32            `db:"odds_history_id" json:"odds_history_id"`
	AlertType        string           `db:"alert_type" json:"alert_type"`
	Severity         string           `db:"severity" json:"severity"`
	Title            string           `db:"title" json:"title"`
	Message          string           `db:"message" json:"message"`
	ChangePercentage pgtype.Numeric   `db:"change_percentage" json:"change_percentage"`
	Multiplier       pgtype.Numeric   `db:"multiplier" json:"multiplier"`
	ConfidenceScore  pgtype.Numeric   `db:"confidence_score" json:"confidence_score"`
	MinutesToKickoff pgtype.Int4      `db:"minutes_to_kickoff" json:"minutes_to_kickoff"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	ExpiresAt        pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	IsActive         pgtype.Bool      `db:"is_active" json:"is_active"`
	Views            pgtype.Int4      `db:"views" json:"views"`
	Clicks           pgtype.Int4      `db:"clicks" json:"clicks"`
}

type OddsHistory struct {
	ID                  int32            `db:"id" json:"id"`
	EventID             pgtype.Int4      `db:"event_id" json:"event_id"`
	MarketTypeID        pgtype.Int4      `db:"market_type_id" json:"market_type_id"`
	Outcome             string           `db:"outcome" json:"outcome"`
	OddsValue           pgtype.Numeric   `db:"odds_value" json:"odds_value"`
	PreviousValue       pgtype.Numeric   `db:"previous_value" json:"previous_value"`
	WinningOdds         pgtype.Numeric   `db:"winning_odds" json:"winning_odds"`
	ChangeAmount        pgtype.Numeric   `db:"change_amount" json:"change_amount"`
	ChangePercentage    pgtype.Numeric   `db:"change_percentage" json:"change_percentage"`
	Multiplier          pgtype.Numeric   `db:"multiplier" json:"multiplier"`
	RecordedAt          pgtype.Timestamp `db:"recorded_at" json:"recorded_at"`
	SharpMoneyIndicator pgtype.Numeric   `db:"sharp_money_indicator" json:"sharp_money_indicator"`
	IsReverseMovement   pgtype.Bool      `db:"is_reverse_movement" json:"is_reverse_movement"`
	SignificanceLevel   pgtype.Text      `db:"significance_level" json:"significance_level"`
	MinutesToKickoff    pgtype.Int4      `db:"minutes_to_kickoff" json:"minutes_to_kickoff"`
}

type OutcomeDistribution struct {
	ID                 int32            `db:"id" json:"id"`
	EventID            pgtype.Int4      `db:"event_id" json:"event_id"`
	MarketID           int32            `db:"market_id" json:"market_id"`
	MarketTypeID       pgtype.Int4      `db:"market_type_id" json:"market_type_id"`
	Outcome            string           `db:"outcome" json:"outcome"`
	BetPercentage      pgtype.Numeric   `db:"bet_percentage" json:"bet_percentage"`
	ImpliedProbability pgtype.Numeric   `db:"implied_probability" json:"implied_probability"`
	ValueIndicator     pgtype.Numeric   `db:"value_indicator" json:"value_indicator"`
	LastUpdated        pgtype.Timestamp `db:"last_updated" json:"last_updated"`
}

type OutcomeDistributionHistory struct {
	ID                 int32            `db:"id" json:"id"`
	EventID            pgtype.Int4      `db:"event_id" json:"event_id"`
	MarketID           int32            `db:"market_id" json:"market_id"`
	Outcome            string           `db:"outcome" json:"outcome"`
	BetPercentage      pgtype.Numeric   `db:"bet_percentage" json:"bet_percentage"`
	PreviousPercentage pgtype.Numeric   `db:"previous_percentage" json:"previous_percentage"`
	ChangeAmount       pgtype.Numeric   `db:"change_amount" json:"change_amount"`
	RecordedAt         pgtype.Timestamp `db:"recorded_at" json:"recorded_at"`
}

type Prediction struct {
	ID               int32            `db:"id" json:"id"`
	EventID          pgtype.Int4      `db:"event_id" json:"event_id"`
	MarketTypeID     pgtype.Int4      `db:"market_type_id" json:"market_type_id"`
	Slug             string           `db:"slug" json:"slug"`
	PredictedOutcome string           `db:"predicted_outcome" json:"predicted_outcome"`
	ConfidenceScore  pgtype.Numeric   `db:"confidence_score" json:"confidence_score"`
	ModelVersion     string           `db:"model_version" json:"model_version"`
	FeaturesUsed     pgtype.Text      `db:"features_used" json:"features_used"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type ReverseLineMovement struct {
	ID                  int32            `db:"id" json:"id"`
	EventID             pgtype.Int4      `db:"event_id" json:"event_id"`
	MarketTypeID        pgtype.Int4      `db:"market_type_id" json:"market_type_id"`
	Outcome             string           `db:"outcome" json:"outcome"`
	OddsValue           pgtype.Numeric   `db:"odds_value" json:"odds_value"`
	PreviousValue       pgtype.Numeric   `db:"previous_value" json:"previous_value"`
	WinningOdds         pgtype.Numeric   `db:"winning_odds" json:"winning_odds"`
	ChangeAmount        pgtype.Numeric   `db:"change_amount" json:"change_amount"`
	ChangePercentage    pgtype.Numeric   `db:"change_percentage" json:"change_percentage"`
	Multiplier          pgtype.Numeric   `db:"multiplier" json:"multiplier"`
	RecordedAt          pgtype.Timestamp `db:"recorded_at" json:"recorded_at"`
	SharpMoneyIndicator pgtype.Numeric   `db:"sharp_money_indicator" json:"sharp_money_indicator"`
	IsReverseMovement   pgtype.Bool      `db:"is_reverse_movement" json:"is_reverse_movement"`
	SignificanceLevel   pgtype.Text      `db:"significance_level" json:"significance_level"`
	MinutesToKickoff    pgtype.Int4      `db:"minutes_to_kickoff" json:"minutes_to_kickoff"`
	EventExternalID     string           `db:"event_external_id" json:"event_external_id"`
	EventDate           pgtype.Timestamp `db:"event_date" json:"event_date"`
	IsLive              pgtype.Bool      `db:"is_live" json:"is_live"`
	MarketCode          string           `db:"market_code" json:"market_code"`
	MarketName          string           `db:"market_name" json:"market_name"`
	HomeTeamName        pgtype.Text      `db:"home_team_name" json:"home_team_name"`
	AwayTeamName        pgtype.Text      `db:"away_team_name" json:"away_team_name"`
	AlertMessage        string           `db:"alert_message" json:"alert_message"`
}

type SharpMoneySpot struct {
	ID                  int32            `db:"id" json:"id"`
	EventID             pgtype.Int4      `db:"event_id" json:"event_id"`
	MarketTypeID        pgtype.Int4      `db:"market_type_id" json:"market_type_id"`
	Outcome             string           `db:"outcome" json:"outcome"`
	OddsValue           pgtype.Numeric   `db:"odds_value" json:"odds_value"`
	PreviousValue       pgtype.Numeric   `db:"previous_value" json:"previous_value"`
	WinningOdds         pgtype.Numeric   `db:"winning_odds" json:"winning_odds"`
	ChangeAmount        pgtype.Numeric   `db:"change_amount" json:"change_amount"`
	ChangePercentage    pgtype.Numeric   `db:"change_percentage" json:"change_percentage"`
	Multiplier          pgtype.Numeric   `db:"multiplier" json:"multiplier"`
	RecordedAt          pgtype.Timestamp `db:"recorded_at" json:"recorded_at"`
	SharpMoneyIndicator pgtype.Numeric   `db:"sharp_money_indicator" json:"sharp_money_indicator"`
	IsReverseMovement   pgtype.Bool      `db:"is_reverse_movement" json:"is_reverse_movement"`
	SignificanceLevel   pgtype.Text      `db:"significance_level" json:"significance_level"`
	MinutesToKickoff    pgtype.Int4      `db:"minutes_to_kickoff" json:"minutes_to_kickoff"`
	EventExternalID     string           `db:"event_external_id" json:"event_external_id"`
	EventDate           pgtype.Timestamp `db:"event_date" json:"event_date"`
	IsLive              pgtype.Bool      `db:"is_live" json:"is_live"`
	MarketCode          string           `db:"market_code" json:"market_code"`
	MarketName          string           `db:"market_name" json:"market_name"`
	HomeTeamName        pgtype.Text      `db:"home_team_name" json:"home_team_name"`
	AwayTeamName        pgtype.Text      `db:"away_team_name" json:"away_team_name"`
	ConfidenceLevel     string           `db:"confidence_level" json:"confidence_level"`
	AlertMessage        string           `db:"alert_message" json:"alert_message"`
}

type SmartMoneyPreference struct {
	ID                  int32            `db:"id" json:"id"`
	UserID              string           `db:"user_id" json:"user_id"`
	MinChangePercentage pgtype.Numeric   `db:"min_change_percentage" json:"min_change_percentage"`
	MinMultiplier       pgtype.Numeric   `db:"min_multiplier" json:"min_multiplier"`
	MinConfidenceScore  pgtype.Numeric   `db:"min_confidence_score" json:"min_confidence_score"`
	BigMoverAlerts      pgtype.Bool      `db:"big_mover_alerts" json:"big_mover_alerts"`
	ReverseLineAlerts   pgtype.Bool      `db:"reverse_line_alerts" json:"reverse_line_alerts"`
	SharpMoneyAlerts    pgtype.Bool      `db:"sharp_money_alerts" json:"sharp_money_alerts"`
	ValueSpotAlerts     pgtype.Bool      `db:"value_spot_alerts" json:"value_spot_alerts"`
	PreferredSports     []byte           `db:"preferred_sports" json:"preferred_sports"`
	PreferredLeagues    []byte           `db:"preferred_leagues" json:"preferred_leagues"`
	MaxDailyAlerts      pgtype.Int4      `db:"max_daily_alerts" json:"max_daily_alerts"`
	PushNotifications   pgtype.Bool      `db:"push_notifications" json:"push_notifications"`
	QuietHoursStart     pgtype.Time      `db:"quiet_hours_start" json:"quiet_hours_start"`
	QuietHoursEnd       pgtype.Time      `db:"quiet_hours_end" json:"quiet_hours_end"`
	CreatedAt           pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Sport struct {
	ID                int32            `db:"id" json:"id"`
	Name              string           `db:"name" json:"name"`
	Code              string           `db:"code" json:"code"`
	Slug              string           `db:"slug" json:"slug"`
	LiveCount         pgtype.Int4      `db:"live_count" json:"live_count"`
	UpcomingCount     pgtype.Int4      `db:"upcoming_count" json:"upcoming_count"`
	EventsCount       pgtype.Int4      `db:"events_count" json:"events_count"`
	OddsCount         pgtype.Int4      `db:"odds_count" json:"odds_count"`
	HasResults        pgtype.Bool      `db:"has_results" json:"has_results"`
	HasKingOdd        pgtype.Bool      `db:"has_king_odd" json:"has_king_odd"`
	HasDigitalContent pgtype.Bool      `db:"has_digital_content" json:"has_digital_content"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Team struct {
	ID                int32            `db:"id" json:"id"`
	ExternalID        string           `db:"external_id" json:"external_id"`
	Name              string           `db:"name" json:"name"`
	Country           pgtype.Text      `db:"country" json:"country"`
	LogoUrl           pgtype.Text      `db:"logo_url" json:"logo_url"`
	IsActive          pgtype.Bool      `db:"is_active" json:"is_active"`
	Slug              pgtype.Text      `db:"slug" json:"slug"`
	ApiFootballID     pgtype.Int4      `db:"api_football_id" json:"api_football_id"`
	TeamCode          pgtype.Text      `db:"team_code" json:"team_code"`
	FoundedYear       pgtype.Int4      `db:"founded_year" json:"founded_year"`
	IsNationalTeam    pgtype.Bool      `db:"is_national_team" json:"is_national_team"`
	VenueID           pgtype.Int4      `db:"venue_id" json:"venue_id"`
	VenueName         pgtype.Text      `db:"venue_name" json:"venue_name"`
	VenueAddress      pgtype.Text      `db:"venue_address" json:"venue_address"`
	VenueCity         pgtype.Text      `db:"venue_city" json:"venue_city"`
	VenueCapacity     pgtype.Int4      `db:"venue_capacity" json:"venue_capacity"`
	VenueSurface      pgtype.Text      `db:"venue_surface" json:"venue_surface"`
	VenueImageUrl     pgtype.Text      `db:"venue_image_url" json:"venue_image_url"`
	ApiEnrichmentData []byte           `db:"api_enrichment_data" json:"api_enrichment_data"`
	LastApiUpdate     pgtype.Timestamp `db:"last_api_update" json:"last_api_update"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type TeamMapping struct {
	ID                   int32            `db:"id" json:"id"`
	InternalTeamID       int32            `db:"internal_team_id" json:"internal_team_id"`
	FootballApiTeamID    int32            `db:"football_api_team_id" json:"football_api_team_id"`
	Confidence           pgtype.Numeric   `db:"confidence" json:"confidence"`
	MappingMethod        string           `db:"mapping_method" json:"mapping_method"`
	TranslatedTeamName   pgtype.Text      `db:"translated_team_name" json:"translated_team_name"`
	TranslatedCountry    pgtype.Text      `db:"translated_country" json:"translated_country"`
	TranslatedLeague     pgtype.Text      `db:"translated_league" json:"translated_league"`
	OriginalTeamName     pgtype.Text      `db:"original_team_name" json:"original_team_name"`
	OriginalCountry      pgtype.Text      `db:"original_country" json:"original_country"`
	OriginalLeague       pgtype.Text      `db:"original_league" json:"original_league"`
	MatchFactors         []byte           `db:"match_factors" json:"match_factors"`
	NeedsReview          pgtype.Bool      `db:"needs_review" json:"needs_review"`
	AiTranslationUsed    pgtype.Bool      `db:"ai_translation_used" json:"ai_translation_used"`
	NormalizationApplied pgtype.Bool      `db:"normalization_applied" json:"normalization_applied"`
	MatchScore           pgtype.Numeric   `db:"match_score" json:"match_score"`
	CreatedAt            pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type ValueSpot struct {
	ID                  int32            `db:"id" json:"id"`
	EventID             pgtype.Int4      `db:"event_id" json:"event_id"`
	MarketTypeID        pgtype.Int4      `db:"market_type_id" json:"market_type_id"`
	Outcome             string           `db:"outcome" json:"outcome"`
	OddsValue           pgtype.Numeric   `db:"odds_value" json:"odds_value"`
	PreviousValue       pgtype.Numeric   `db:"previous_value" json:"previous_value"`
	WinningOdds         pgtype.Numeric   `db:"winning_odds" json:"winning_odds"`
	ChangeAmount        pgtype.Numeric   `db:"change_amount" json:"change_amount"`
	ChangePercentage    pgtype.Numeric   `db:"change_percentage" json:"change_percentage"`
	Multiplier          pgtype.Numeric   `db:"multiplier" json:"multiplier"`
	RecordedAt          pgtype.Timestamp `db:"recorded_at" json:"recorded_at"`
	SharpMoneyIndicator pgtype.Numeric   `db:"sharp_money_indicator" json:"sharp_money_indicator"`
	IsReverseMovement   pgtype.Bool      `db:"is_reverse_movement" json:"is_reverse_movement"`
	SignificanceLevel   pgtype.Text      `db:"significance_level" json:"significance_level"`
	MinutesToKickoff    pgtype.Int4      `db:"minutes_to_kickoff" json:"minutes_to_kickoff"`
	BetPercentage       pgtype.Numeric   `db:"bet_percentage" json:"bet_percentage"`
	ImpliedProbability  pgtype.Numeric   `db:"implied_probability" json:"implied_probability"`
	EventExternalID     string           `db:"event_external_id" json:"event_external_id"`
	EventDate           pgtype.Timestamp `db:"event_date" json:"event_date"`
	MarketCode          string           `db:"market_code" json:"market_code"`
	MarketName          string           `db:"market_name" json:"market_name"`
	HomeTeamName        pgtype.Text      `db:"home_team_name" json:"home_team_name"`
	AwayTeamName        pgtype.Text      `db:"away_team_name" json:"away_team_name"`
	PublicBias          int32            `db:"public_bias" json:"public_bias"`
	AlertMessage        string           `db:"alert_message" json:"alert_message"`
}
